kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kenmoini-com-ingress
  namespace: kenmoini-com
  labels:
    app: kenmoini-com
    app.kubernetes.io/name: kenmoini-com
    app.kubernetes.io/part-of: kenmoini-com
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - www.kenmoini.com
      secretName: kenmoini-com-www-tls
  rules:
    - host: www.kenmoini.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kenmoini-com-svc
              servicePort: 8080