paginate: 8

social:
  twitter: "kenmoini"
  github: "kenmoini"
  linkedin: "kenmoini"
  youtube: "https://www.youtube.com/channel/UCVP0QIDEIZTmxW04-p9QduQ"

taxonomies:
  author: authors

outputs:
  home:
  - html
  - rss
  section:
  - html
  - rss
  taxonomy:
  - html
  term:
  - html

title: "Ken Moini"
baseURL: "https://kenmoini.com"
languageCode: "en-us"
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
  fr:
    languageName: Français
    weight: 2
    contentDir: content/fr
  es:
    languageName: Spanish
    weight: 3
    contentDir: content/es

theme: novela
disqusShortname: kenmoini
params:
  description: The digital residence of parts of my mind. I work on things that live on the Internet, practice modern alchemy, and dabble in danger.
#  seo:
#    default_image:

markup:
  highlight:
    codeFences: false
    guessSyntax: false
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: none
    tabWidth: 2
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
