paginate: 8

social:
  twitter: "https://twitter.com/kenmoini"
  github: "https://github.com/kenmoini"
  linkedin: "https://www.linkedin.com/in/kenmoini"
  youtube: "https://www.youtube.com/channel/UCVP0QIDEIZTmxW04-p9QduQ"

taxonomies:
  author: authors

baseURL: "https://kenmoini.com"
languageCode: "en-us"
title: "Ken Moini"
pygmentsstyle: 'monokai'
theme: novela
disqusShortname: kenmoini

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    style: monokai
    tabWidth: 2