apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ken@kenmoini.com
    privateKeySecretRef:
      name: letsencrypt-dns-prod
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: do-dns-pat
            key: access-token